      name: Deploy via ftp pagina principal
      on: push
      jobs:
        deploy:
          name: Deploy
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2

          - name: FTP Deploy WebHost
            uses: SamKirkland/FTP-Deploy-Action@4.1.0
            with:
              host: ${{ secrets.ftp_HOST }} 
              user: ${{ secrets.ftp_USER }}
              password: ${{ secrets.ftp_PASS }}
              server-dir: /public_html
              remoteDir: /public_html
