      name: Deploy via ftp pagina principal
      on: push
      jobs:
        deploy:
          name: Deploy
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2

          - name: FTP Deploy 000Webhost
            run: |
               sudo apt-get update
               sudo apt-get install lftp -y
                run: |
                    lftp -c "set ftp:ssl-allow no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; mirror -R -e ./public_html /public_html"
